// Generated by Wrangler on Tue Jul 09 2024 21:58:57 GMT+0800 (Taipei Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	R2: R2Bucket;
	DB: D1Database;
}
